# Generated by Django 3.1.6 on 2021-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210213_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='moderator',
            new_name='moderators',
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
